# Generated by Django 4.1.6 on 2024-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_alter_appointment_calltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='calltime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
